const autoCompleteJS = new autoComplete({
	placeHolder: 'Buscador de herramientas por nombre, modelo y capacidad...',
	data: {
		src: [
			{
				id: 1,
				nombre: 'Torquimetros  de golpe encastre 1/4',
				marca: 'WRIGHT',
				modelo: 'modelo 2477',
				max: '150',
				capacidad: '20-150 Lbs-pulg/2.8-16.4 Nm',
				longitud: '10.15',
				peso: '0.9 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 2,
				nombre: 'Torquimetros  de golpe encastre 3/8',
				marca: 'WRIGHT',
				modelo: 'modelo 3447',
				max: '75',
				capacidad: '5-75 Lbs-pie/10.2-98.3 Nm',
				longitud: '15.15',
				peso: '2.5 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 3,
				nombre: 'Torquimetros  de golpe encastre 3/8',
				marca: 'WRIGHT',
				modelo: 'modelo 3477',
				max: '100',
				capacidad: '10-100 Lbs-pie/16.9-132.2 Nm',
				longitud: '15.15',
				peso: '2.5 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 4,
				nombre: 'Torquimetros  de golpe encastre 3/8',
				marca: 'WRIGHT',
				modelo: 'modelo 3478',
				max: '200',
				capacidad: '30-200 Lbs-pulg/3.9-22 Nm',
				longitud: '10.15',
				peso: '0.85 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 5,
				nombre: 'Torquimetros  de golpe encastre 3/8',
				marca: 'WRIGHT',
				modelo: 'modelo 3479',
				max: '1000',
				capacidad: '150-1000 Lbs-pulg/19.8-110.2 Nm',
				longitud: '15.75',
				peso: '2.5 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 6,
				nombre: 'Torquimetros  de golpe encastre 1/2',
				marca: 'WRIGHT',
				modelo: 'modelo 4476',
				max: '1600',
				capacidad: '700-1600 Lbs-pie/84.4-175.2 Nm',
				longitud: '18',
				peso: '3.0 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 7,
				nombre: 'Torquimetros  de gople encastre 1/2',
				marca: 'WRIGHT',
				modelo: 'modelo 4477',
				max: '150',
				capacidad: '20-150 Lbs-pie/34-197 Nm',
				longitud: '19',
				peso: '3.15 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 8,
				nombre: 'Torquimetros  de golpe encastre 1/2',
				marca: 'WRIGHT',
				modelo: 'modelo 4478',
				max: '250',
				capacidad: '50-250 Lbs-pie/47-332.2 Nm',
				longitud: '24.4',
				peso: '3.15 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 9,
				nombre: 'Torquimetros  de golpe encastre 3/4',
				marca: 'WRIGHT',
				modelo: 'modelo 6448',
				max: '600',
				capacidad: '100-600 Lbs-pie/169-779 Nm',
				longitud: '42',
				peso: '8.95 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 10,
				nombre: 'Torquimetros  de golpe encastre 1',
				marca: 'WRIGHT',
				modelo: 'modelo 8447',
				max: '1000',
				capacidad: '200-1000 Lbs-pie/305-1320 Nm',
				longitud: '70',
				peso: '40 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 11,
				nombre: 'Torquimetros  de golpe encastre 1',
				marca: 'WRIGHT',
				modelo: 'modelo 8448',
				max: '1000',
				capacidad: '200-1000 Lbs-pie/305-1320 Nm',
				longitud: '69',
				peso: '24.5 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe c.jpg',
			},
			{
				id: 12,
				nombre: 'Torquimetros  de golpe encastre 1',
				marca: 'WRIGHT',
				modelo: 'modelo 8449',
				max: '2000',
				capacidad: '300-2000 Lbs-pie/480-2700 Nm',
				longitud: '108-1/2',
				peso: '48.75 Lbs',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe d.jpg',
			},
			{
				id: 13,
				nombre: 'Torquimetros de reloj encastre 1/4',
				encastre: '1/4',
				tipo: 'RATCHET',
				max: '30',
				modelo: 'modelo 2470',
				capacidad: '0-30 LBS-pulg/0-3.5 Nm',
				longitud: '10',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '1 Lbs',
			},
			{
				id: 14,
				nombre: 'Torquimetros de reloj encastre 1/2',
				encastre: '1/2',
				tipo: 'RATCHET',
				max: '250',
				modelo: 'modelo 4471',
				capacidad: '0-250 LBS-pulg/0-350 Nm',
				longitud: '21-1/2',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '2-3/4 Lbs',
			},
			{
				id: 15,
				nombre: 'Torquimetros de reloj encastre 3/8',
				encastre: '3/8',
				tipo: 'RATCHET',
				max: '150',
				modelo: 'modelo 3470',
				capacidad: '0-150 LBS-pulg/0-18 Nm',
				longitud: '10',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '1 Lbs',
			},
			{
				id: 16,
				nombre: 'Torquimetros de reloj encastre 3/8',
				encastre: '3/8',
				tipo: 'RATCHET',
				max: '250',
				modelo: 'modelo 3471',
				capacidad: '0-250 LBS-pulg/0-30 Nm',
				longitud: '10',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '1 Lbs',
			},
			{
				nombre: 'Torquimetros de reloj encastre 3/8',
				encastre: '3/8',
				tipo: 'RATCHET',
				max: '50',
				modelo: 'modelo 3473',
				capacidad: '0-50 LBS-pie/0-70 Nm',
				longitud: '14-7/8',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '1-3/4 Lbs',
			},
			{
				id: 17,
				nombre: 'Torquimetros de reloj encastre 1/2',
				encastre: '1/2',
				tipo: 'RATCHET',
				max: '175',
				modelo: 'modelo 4470',
				capacidad: '0-175 LBS-pie/0-240 Nm',
				longitud: '21-1/2',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '2-3/4 Lbs',
			},
			{
				id: 18,
				nombre: 'Torquimetros de reloj encastre 1/2',
				encastre: '1/2',
				tipo: 'RATCHET',
				max: '250',
				modelo: 'modelo 4471',
				capacidad: '0-250 LBS-pulg/0-350 Nm',
				longitud: '21-1/2',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '2-3/4 Lbs',
			},
			{
				id: 19,
				nombre: 'Torquimetros de reloj encastre 3/4',
				encastre: '3/4',
				tipo: 'RATCHET',
				max: '600',
				modelo: 'modelo 6470',
				capacidad: '0-600 LBS-pie/0-800 Nm',
				longitud: '46-1/2',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj b.jpg',
				peso: '9-1/4 Lbs',
			},
			{
				id: 20,
				nombre: 'Torquimetros de reloj encastre 3/4',
				encastre: '3/4',
				tipo: 'RATCHET',
				max: '350',
				modelo: 'modelo 6471',
				capacidad: '0-350 LBS-pie/0-480 Nm',
				longitud: '27-7/8',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj b.jpg',
				peso: '5-3/4 Lbs',
			},
			{
				id: 21,
				nombre: 'Torquimetros de reloj encastre 3/4',
				encastre: '3/4',
				tipo: 'RATCHET',
				max: '600',
				modelo: 'modelo 6472',
				capacidad: '0-600 LBS-pulg/0-800 Nm',
				longitud: '46-1/2',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj c.jpg',
				peso: '9-1/4 Lbs',
			},
			{
				id: 22,
				nombre: 'Torquimetros de reloj encastre 1',
				encastre: '1',
				tipo: 'RATCHET',
				max: '1000',
				modelo: 'modelo 8470',
				capacidad: '0-1000 LBS-pulg/0-1400 Nm',
				longitud: '74',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj b.jpg',
				peso: '18-1/2 Lbs',
			},
			{
				id: 23,
				nombre: 'Torquimetros de reloj encastre 1',
				encastre: '1',
				tipo: 'RATCHET',
				max: '1000',
				modelo: 'modelo 8471',
				capacidad: '0-1000 LBS-pulg/0-1400 Nm',
				longitud: '74',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj c.jpg',
				peso: '18-1/2 Lbs',
			},
			{
				id: 24,
				nombre: 'Torquimetros de reloj encastre 1',
				encastre: '1',
				tipo: 'RATCHET',
				max: '2000',
				modelo: 'modelo 8472',
				capacidad: '0-2000 LBS-pulg/0-1400 Nm',
				longitud: '122',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj d.jpg',
				peso: '44-1/2 Lbs',
			},
			{
				id: 25,
				nombre: 'Artornillador digital encaste hexagonal 1/4',
				encastre: '1/4"',
				max: '15',
				tipo: 'RATCHET',
				modelo: 'modelo 2463',
				capacidad: '3-15 Lb-pulg',
				longitud: '8"',
				url: 'torquimetros-destornillador.html',
				img: './images/torquimetros/torquimetro destornillador/atornillador.jpg',
				peso: '1 Lbs',
			},
			{
				id: 26,
				nombre: 'Artornillador digital encaste hexagonal 1/4',
				encastre: '1/4"',
				max: '40',
				tipo: 'RATCHET',
				modelo: 'modelo 2464',
				capacidad: '5-40 Lb-pulg',
				longitud: '8"',
				url: 'torquimetros-destornillador.html',
				img: './images/torquimetros/torquimetro destornillador/atornillador.jpg',
				peso: '1 Lbs',
			},
			{
				id: 27,
				nombre: 'Torquimetro digital inalambrico encaste 3/8',
				encastre: '3/8"',
				max: '100',
				tipo: 'Ratchet digital',
				modelo: 'modelo 2465',
				capacidad: '10-100 LB-pie/13.5-135.5 Nm',
				longitud: '23.3"',
				url: 'torquimetros-digital-inalambrico.html',
				img: './images/torquimetros/torquimetro digital/torquimetro digital inalambrico.jpg',
				peso: '5.5 Lbs',
			},
			{
				id: 28,
				nombre: 'Torquimetro digital inalambrico encaste 1/2',
				encastre: '1/2"',
				max: '150',
				tipo: 'Ratchet digital',
				modelo: 'modelo 2466',
				capacidad: '12.5-150 LB-pie/17-203 Nm',
				longitud: '23.5"',
				url: 'torquimetros-digital-inalambrico.html',
				img: './images/torquimetros/torquimetro digital/torquimetro digital inalambrico.jpg',
				peso: '5.7 Lbs',
			},
			{
				id: 29,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S290P',
				'encastre de entrada': '1/2"',
				'encastre de salida': '3/4"',
				'Torque de entrada': '227 Lbs-pie',
				'Torque de salida': '750 Lbs-pie',
				capacidad: '227-750 Lbs',
				proporcion: '3.0:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador a.jpg',
				peso: '4-7/8 Lbs',
			},
			{
				id: 30,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S291',
				'encastre de entrada': '1/2"',
				'encastre de salida': '3/4"',
				'Torque de entrada': '303 Lbs-pie',
				'Torque de salida': '1000 Lbs-pie',
				capacidad: '303-1000 Lbs',
				proporcion: '3.3:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador b.jpg',
				peso: '5-7/8 Lbs',
			},
			{
				id: 31,
				nombre: 'Multiplicador de torque encastre 3/4',
				modelo: 'modelo 9S292',
				'encastre de entrada': '3/4"',
				'encastre de salida': '1"',
				'Torque de entrada': '571 Lbs-pie',
				'Torque de salida': '2000 Lbs-pie',
				capacidad: '571-2000 Lbs',
				proporcion: '3.75:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador c.jpg',
				peso: '13-7/8 Lbs',
			},
			{
				id: 32,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S391',
				'encastre de entrada': '1/2"',
				'encastre de salida': '3/4"',
				'Torque de entrada': '200 Lbs-pie',
				'Torque de salida': '1200 Lbs-pie',
				capacidad: '200-1200 Lbs',
				proporcion: '6:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador d.jpg',
				peso: '13 Lbs',
			},
			{
				id: 33,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S392B',
				'encastre de entrada': '1/2"',
				'encastre de salida': '1"',
				'Torque de entrada': '162 Lbs-pie',
				'Torque de salida': '2200 Lbs-pie',
				capacidad: '162-2200 Lbs',
				proporcion: '13.6:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador e.jpg',
				peso: '20-5/8 Lbs',
			},
			{
				id: 34,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S393A',
				'encastre de entrada': '1/2"',
				'encastre de salida': '1"',
				'Torque de entrada': '173 Lbs-pie',
				'Torque de salida': '3200 Lbs-pie',
				capacidad: '173-3200 Lbs',
				proporcion: '18.5:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador e.jpg',
				peso: '22-3/8 Lbs',
			},
			{
				id: 35,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S394',
				'encastre de entrada': '1/2"',
				'encastre de salida': '1-1/2"',
				'Torque de entrada': '189 Lbs-pie',
				'Torque de salida': '5000 Lbs-pie',
				capacidad: '189-5000 Lbs',
				proporcion: '26.5:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador f.jpg',
				peso: '34.0 Lbs',
			},
			{
				id: 36,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S395',
				'encastre de entrada': '1/2"',
				'encastre de salida': '1-1/2"',
				'Torque de entrada': '154 Lbs-pie',
				'Torque de salida': '8000 Lbs-pie',
				capacidad: '154-8000 Lbs',
				proporcion: '52.0:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador f.jpg',
				peso: '50.3 Lbs',
			},
			{
				id: 37,
				nombre: 'Multiplicador de torque encastre 1/2',
				modelo: 'modelo 9S492',
				'encastre de entrada': '1/2"',
				'encastre de salida': '1"',
				'Torque de entrada': '162 Lbs-pie',
				'Torque de salida': '2200 Lbs-pie',
				capacidad: '162-2200 Lbs',
				proporcion: '13.6:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador g.jpg',
				peso: '17.2 Lbs',
			},
			{
				id: 38,
				nombre: 'Llave de control de torque electricas encastre 3/4',
				'Art N°': '50 084 103',
				encastre: '3/4 ó 1"',
				max: '850',
				modelo: 'modelo TESM-84',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '150-850 Nm',
				peso: '9.8/10 kg ',
			},
			{
				id: 39,
				nombre: 'Llave de control de torque electricas encastre 1',
				'Art N°': '50 105 113',
				encastre: '1"',
				max: '1200',
				modelo: 'modelo TESM-105',
				velocidad: '5 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '280-1200 Nm',
				peso: '10 Kg',
			},
			{
				id: 40,
				nombre: 'Llave de control de torque electricas encastre 1.1/2',
				'Art N°': '50 335 133',
				encastre: '1.1/2"',
				max: '3500',
				modelo: 'modelo TESM-355',
				velocidad: '3 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '360-3500 Nm',
				peso: '14.5 Kg',
			},
			{
				id: 41,
				nombre: 'Llave de control de torque electricas encastre 1.1/2',
				'Art N°': '50 505 143',
				encastre: '1.1/2"',
				max: '700',
				modelo: 'modelo TESM-505',
				velocidad: '1.2 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '50-700 Nm',
				peso: '16.7 Kg',
			},
			{
				id: 42,
				nombre: 'Llave de control de torque inalambrico encastre 3/4',
				encastre: '3/4"',
				max: '1300',
				modelo: 'CP8613',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica a.jpg',
				capacidad: '300-1300 Nm',
				peso: '5.3 Kg / 11.7 Lbs',
			},
			{
				id: 43,
				nombre: 'Llave de control de torque inalambrico encastre 1',
				encastre: '1"',
				max: '2600',
				modelo: 'CP8626',
				velocidad: '5 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica b.jpg',
				capacidad: '700-2600 Nm',
				peso: '7.2 Kg / 15.9 Lbs',
			},
			{
				id: 44,
				nombre: 'Llave de control de torque inalambrico encastre 1',
				encastre: '1"',
				max: '4100',
				modelo: 'CP8641',
				velocidad: '3 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica c.jpg',
				capacidad: '1000-4100 Nm',
				peso: '11.4 Kg / 25.13 Lbs',
			},
			{
				id: 45,
				nombre: 'Llave de control de torque inalambrico encastre 1 ó 1.1/2',
				encastre: '1" ó 1.1/2"',
				max: '8100',
				modelo: 'CP8681',
				velocidad: '1.2 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica d.jpg',
				capacidad: '2600-8100 Nm',
				peso: '16.5 Kg / 36.4 Lbs',
			},
			{
				id: 46,
				nombre: 'Llave de control de torque neumatica encastre 3/4',
				'Art N°': '615 180 0120',
				max: '1300',
				modelo: 'CP6613',
				encastre: '3/4"',
				velocidad: '20 RPM',
				url: 'llave-de-control-de-torque-neumatica.html',
				img: './images/llave/multiplicador/multiplicador.jpg',
				capacidad: '320-1300 Nm',
				peso: '4.4 Kg / 9.7 Lbs',
			},
			{
				id: 47,
				nombre: 'Llave de control de torque neumatica encastre 1"',
				'Art N°': '615 180 0130',
				max: '2600',
				modelo: 'CP6626',
				encastre: '1"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-neumatica.html',
				img: './images/llave/multiplicador/multiplicador.jpg',
				capacidad: '700-2600 Nm',
				peso: '5.7 Kg / 12.5 Lbs',
			},
			{
				id: 48,
				nombre: 'Llave de control de torque neumatica encastre 1"',
				'Art N°': '615 180 0140',
				max: '4100',
				modelo: 'CP6641',
				encastre: '1"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-neumatica.html',
				img: './images/llave/multiplicador/multiplicador.jpg',
				capacidad: '1000-4100 Nm',
				peso: '11.4 Kg / 25.13 Lbs',
			},
			{
				id: 49,
				nombre: 'Llave de control de torque hidraulica encastre 1 o 1.1/2"',
				'Art N°': '71 051 000',
				max: '4900',
				modelo: 'BL-51',
				encastre: '1 ó 1.1/2"',
				velocidad: '20 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '320-4900 Nm',
				peso: '4.9 Kg',
			},
			{
				id: 50,
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2"',
				'Art N°': '71 052 000',
				max: '5200',
				modelo: 'BL-52',
				encastre: '1.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '320-5200 Nm',
				peso: '5.4 Kg',
			},
			{
				id: 51,
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2"',
				'Art N°': '71 082 000',
				max: '4100',
				modelo: 'BL-82',
				encastre: '1.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '1000-4100 Nm',
				peso: '7.8 Kg',
			},
			{
				id: 52,
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2"',
				'Art N°': '71 102 000',
				max: '1000',
				modelo: 'BL-102',
				encastre: '1.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '440-1000 Nm',
				peso: '7.8 Kg',
			},
			{
				id: 53,
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2 ó 2.1/2"',
				'Art N°': '71 152 000',
				max: '15200',
				modelo: 'BL-152',
				encastre: '1.1/2 ó 2.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '950-15200 Nm',
				peso: '12 Kg',
			},
		],
		keys: ['nombre', 'modelo', 'capacidad'],
		cache: true,
		submit: true,
	},
	resultsList: {
		element: (list, data) => {
			if (!data.results.length) {
				// Create "No Results" message element
				const message = document.createElement('div');
				// Add class to the created element
				message.setAttribute('class', 'no_result');
				// Add message text content
				message.innerHTML = `<span>Found No Results for "${data.query}"</span>`;
				// Append message element to the results list
				list.prepend(message);
			}
		},
		noResults: true,
		maxResults: 50,
		tabSelect: true,
	},
	resultItem: {
		highlight: true,
	},
	events: {
		input: {
			selection: (event) => {
				console.log(event, 'aqui esta el evento');
				const selection = event.detail.selection.value;
				autoCompleteJS.input.value = selection.nombre;
				let containerList = document.getElementById('list-items');

				containerList.innerHTML = `
				<a href="${selection.url}"  class="list-items__container-item" id="">
						<img class="img-herramientas" src="${selection.img}" alt="" srcset="" />
						<h3>${selection.nombre}</h3>
						<p>${selection.modelo}</p>
						<div class="list-items__content" id="list-items__content">
							<p><b>capacidad:</b>  ${selection.capacidad}</p>
							<p><b>peso:</b> ${selection.peso}</p>
						</div>
					</a>
					`;
			},
		},
	},
});
