const autoCompleteJS = new autoComplete({
	placeHolder: 'Nombre, modelo y capacidad...',
	data: {
		src: [
			{
				id: 1,
				alt: 'Torquimetros  de golpe encastre 1/4',
				nombre: 'Torquimetros  de golpe encastre 1/4"',
				marca: 'WRIGHT',
				modelo: 'modelo 2477',
				max: '12',
				min: '2',
				capacidad: '2.5 - 12.5 Lbs-pie / 3.40 - 16.90 Nm',
				longitud: '10"',
				peso: '0.40 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
				alt: 'Torquimetros de golpe encastre 1/4',
			},
			{
				id: 2,
				alt: 'Torquimetros  de golpe encastre 3/8',
				nombre: 'Torquimetros  de golpe encastre 3/8"',
				marca: 'WRIGHT',
				modelo: 'modelo 3447',
				max: '75',
				min: '15',
				capacidad: '15 - 75 Lbs-pie / 20.30 - 101.70 Nm',
				longitud: '15.15"',
				peso: '1.13 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 3,
				alt: 'Torquimetros  de golpe encastre 3/8',
				nombre: 'Torquimetros  de golpe encastre 3/8"',
				marca: 'WRIGHT',
				modelo: 'modelo 3477',
				max: '100',
				min: '20',
				capacidad: '20 - 100 Lbs-pie / 27.10 - 135.60 Nm',
				longitud: '15.15"',
				peso: '1.13 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 4,
				alt: 'Torquimetros  de golpe encastre 3/8',
				nombre: 'Torquimetros  de golpe encastre 3/8"',
				marca: 'WRIGHT',
				modelo: 'modelo 3478',
				max: '16',
				min: '3',
				capacidad: '3.33 - 16.66 Lbs-pie / 4.50 - 22.60 Nm',
				longitud: '10"',
				peso: '0.38 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 5,
				alt: 'Torquimetros  de golpe encastre 3/8',
				nombre: 'Torquimetros  de golpe encastre 3/8"',
				marca: 'WRIGHT',
				modelo: 'modelo 3479',
				max: '83',
				min: '16',
				capacidad: '16.66 - 83.33 Lbs-pie / 22.60-113 Nm',
				longitud: '15.5"',
				peso: '1.13 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe a.jpg',
				tag: 'top',
			},
			{
				id: 6,
				alt: 'Torquimetros  de golpe encastre 1/2',
				nombre: 'Torquimetros  de golpe encastre 1/2"',
				marca: 'WRIGHT',
				modelo: 'modelo 4476',
				max: '133',
				min: '58',
				capacidad: '58.33 - 133.33 Lbs-pie / 79.10-180.80 Nm',
				longitud: '19"',
				peso: '1.36 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 7,
				alt: 'Torquimetros  de golpe encastre 1/2',
				nombre: 'Torquimetros  de gople encastre 1/2"',
				marca: 'WRIGHT',
				modelo: 'modelo 4477',
				max: '150',
				min: '30',
				capacidad: '30 - 150 Lbs-pie / 40.70 - 203.40 Nm',
				longitud: '19"',
				peso: '1.42 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 8,
				alt: 'Torquimetros  de golpe encastre 1/2',
				nombre: 'Torquimetros  de golpe encastre 1/2"',
				marca: 'WRIGHT',
				modelo: 'modelo 4478',
				max: '250',
				min: '50',
				capacidad: '50 - 250 Lbs-pie / 67.80 - 339 Nm',
				longitud: '24"',
				peso: '1.42 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
				tag: 'top',
			},
			{
				id: 9,
				alt: 'Torquimetros  de golpe encastre 3/4',
				nombre: 'Torquimetros  de golpe encastre 3/4"',
				marca: 'WRIGHT',
				modelo: 'modelo 6448',
				max: '600',
				min: '120',
				capacidad: '120 - 600 Lbs-pie /  163 - 813 Nm',
				longitud: '41"',
				peso: '4.05 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
			},
			{
				id: 10,
				alt: 'Torquimetros  de golpe encastre 1',
				nombre: 'Torquimetros  de golpe encastre 1"',
				marca: 'WRIGHT',
				modelo: 'modelo 8447',
				max: '1000',
				min: '200',
				capacidad: '200 - 1000 Lbs-pie / 271 - 1356 Nm',
				longitud: '70"',
				peso: '18.14 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe b.jpg',
			},
			{
				id: 11,
				alt: 'Torquimetros  de golpe encastre 1',
				nombre: 'Torquimetros  de golpe encastre 1"',
				marca: 'WRIGHT',
				modelo: 'modelo 8448',
				max: '1000',
				min: '200',
				capacidad: '200 - 1000 Lbs-pie / 271 - 1356 Nm',
				longitud: '70',
				peso: '11.11 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe c.jpg',
			},
			{
				id: 12,
				alt: 'Torquimetros  de golpe encastre 1',
				nombre: 'Torquimetros  de golpe encastre 1"',
				marca: 'WRIGHT',
				modelo: 'modelo 8449',
				max: '2000',
				min: '400',
				capacidad: '400 - 2000 Lbs-pie / 542.33 - 2711.64 Nm',
				longitud: '108"',
				peso: '22.11 Kg',
				tipo: 'Ratchet',
				url: 'torquimetros-de-golpe.html',
				img: './images/torquimetros/torquimetros de golpe/torquimetros de golpe d.jpg',
			},
			{
				id: 13,
				alt: 'Torquimetros de reloj encastre 1/4',
				nombre: 'Torquimetros de reloj encastre 1/4"',
				encastre: '1/4',
				tipo: 'RATCHET',
				max: '2',
				min: '1',
				modelo: 'modelo 2470',
				capacidad: '0.5 - 2.5 Lbs-pie /  0.70 - 3.40 Nm',
				longitud: '11.25"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '0.45 Kg',
			},
			{
				id: 14,
				alt: 'Torquimetros de reloj encastre 3/8',
				nombre: 'Torquimetros de reloj encastre 3/8"',
				encastre: '3/8',
				tipo: 'RATCHET',
				max: '12',
				min: '2',
				modelo: 'modelo 3470',
				capacidad: '2.5 - 12.5 Lbs-pie / 3 - 17 Nm',
				longitud: '11.25"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '0.45 Kg',
			},
			{
				id: 15,
				alt: 'Torquimetros de reloj encastre 3/8',
				nombre: 'Torquimetros de reloj encastre 3/8"',
				encastre: '3/8',
				tipo: 'RATCHET',
				max: '20',
				min: '4',
				modelo: 'modelo 3471',
				capacidad: '4.16 - 20.8 Lbs-pie / 6 - 28 Nm',
				longitud: '11.25"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '0.45 Kg',
			},
			{
				id: 16,
				alt: 'Torquimetros de reloj encastre 3/8',
				nombre: 'Torquimetros de reloj encastre 3/8"',
				encastre: '3/8',
				tipo: 'RATCHET',
				max: '50',
				min: '10',
				modelo: 'modelo 3473',
				capacidad: '10 - 50 Lbs-pie / 14 - 68 Nm',
				longitud: '14.88"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '0.79 Kg',
			},
			{
				id: 17,
				alt: 'Torquimetros de reloj encastre 1/2',
				nombre: 'Torquimetros de reloj encastre 1/2"',
				encastre: '1/2',
				tipo: 'RATCHET',
				max: '175',
				min: '35',
				modelo: 'modelo 4470',
				capacidad: '35 - 175 Lbs-pie / 47 - 237 Nm',
				longitud: '21.75"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '1.24 Kg',
			},
			{
				id: 18,
				alt: 'Torquimetros de reloj encastre 1/2',
				nombre: 'Torquimetros de reloj encastre 1/2"',
				encastre: '1/2',
				tipo: 'RATCHET',
				max: '250',
				min: '50',
				modelo: 'modelo 4471',
				capacidad: '50 - 250 Lbs-pie / 68 - 339 Nm',
				longitud: '21.75"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj a.jpg',
				peso: '1.24 Kg',
			},
			{
				id: 19,
				alt: 'Torquimetros de reloj encastre 3/4',
				nombre: 'Torquimetros de reloj encastre 3/4"',
				encastre: '3/4',
				tipo: 'RATCHET',
				max: '600',
				min: '120',
				modelo: 'modelo 6470',
				capacidad: '120 - 600 Lbs-pie / 160 - 800 Nm',
				longitud: '46.75"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj b.jpg',
				peso: '4.19 Kg',
			},
			{
				id: 20,
				alt: 'Torquimetros de reloj encastre 3/4',
				nombre: 'Torquimetros de reloj encastre 3/4"',
				encastre: '3/4',
				tipo: 'RATCHET',
				max: '350',
				min: '70',
				modelo: 'modelo 6471',
				capacidad: '70 - 350 Lbs-pie / 95 - 475 Nm',
				longitud: '28"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj b.jpg',
				peso: '2.60 Kg',
			},
			{
				id: 21,
				alt: 'Torquimetros de reloj encastre 3/4',
				nombre: 'Torquimetros de reloj encastre 3/4"',
				encastre: '3/4',
				tipo: 'RATCHET',
				max: '600',
				min: '120',
				modelo: 'modelo 6472',
				capacidad: '120 - 600 Lbs-pie / 160 - 800 Nm',
				longitud: '46.75"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj c.jpg',
				peso: '4.19 Kg',
			},
			{
				id: 22,
				alt: 'Torquimetros de reloj encastre 1',
				nombre: 'Torquimetros de reloj encastre 1"',
				encastre: '1',
				tipo: 'RATCHET',
				max: '1000',
				min: '200',
				modelo: 'modelo 8470',
				capacidad: '200 - 1000 Lbs-pie / 271 - 1356 Nm',
				longitud: '74"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj b.jpg',
				peso: '8.39 Kg',
			},
			{
				id: 23,
				alt: 'Torquimetros de reloj encastre 1',
				nombre: 'Torquimetros de reloj encastre 1"',
				encastre: '1',
				tipo: 'RATCHET',
				max: '1000',
				min: '200',
				modelo: 'modelo 8471',
				capacidad: '200 - 1000 Lbs-pie / 271 - 1356 Nm',
				longitud: '74"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj c.jpg',
				peso: '8.39 Kg',
			},
			{
				id: 24,
				alt: 'Torquimetros de reloj encastre 1',
				nombre: 'Torquimetros de reloj encastre 1"',
				encastre: '1',
				tipo: 'RATCHET',
				max: '2000',
				min: '400',
				modelo: 'modelo 8472',
				capacidad: '400 - 2000 Lbs-pie / 542 - 2712 Nm',
				longitud: '122"',
				url: 'torquimetros-de-reloj.html',
				img: './images/torquimetros/torquimetro de reloj/torquimetros reloj d.jpg',
				peso: '20.18 Kg',
			},
			{
				id: 25,
				alt: 'Artornillador digital encaste hexagonal 1/4',
				nombre: 'Artornillador digital encaste hexagonal 1/4"',
				encastre: '1/4"',
				max: '1',
				min: '1',
				tipo: 'RATCHET',
				modelo: 'modelo 2463',
				capacidad: '0.25 - 1.25 Lbs-pie / 0.33 - 1.69 Nm',
				longitud: '8"',
				url: 'torquimetros-destornillador.html',
				img: './images/torquimetros/torquimetro destornillador/atornillador.jpg',
				peso: '0.45 Kg',
			},
			{
				id: 26,
				alt: 'Artornillador digital encaste hexagonal 1/4',
				nombre: 'Artornillador digital encaste hexagonal 1/4"',
				encastre: '1/4"',
				max: '3',
				min: '1',
				tipo: 'RATCHET',
				modelo: 'modelo 2464',
				capacidad: '0.41 - 3.33 Lbs-pie / 0.55 - 4.51 Nm',
				longitud: '8"',
				url: 'torquimetros-destornillador.html',
				img: './images/torquimetros/torquimetro destornillador/atornillador.jpg',
				peso: '0.45 Kg',
			},
			{
				id: 27,
				alt: 'Torquimetro digital inalambrico encaste 3/8',
				nombre: 'Torquimetro digital inalambrico encaste 3/8"',
				encastre: '3/8"',
				max: '100',
				min: '10',
				tipo: 'Ratchet digital',
				modelo: 'modelo 2465',
				capacidad: '10 - 100 Lbs-pie / 13.5-135.5 Nm',
				longitud: '23.3"',
				url: 'torquimetros-digital-inalambrico.html',
				img: './images/torquimetros/torquimetro digital/torquimetro digital inalambrico.jpg',
				peso: '2.49 Kg',
			},
			{
				id: 28,
				alt: 'Torquimetro digital inalambrico encaste 1/2',
				nombre: 'Torquimetro digital inalambrico encaste 1/2"',
				encastre: '1/2"',
				max: '150',
				min: '12',
				tipo: 'Ratchet digital',
				modelo: 'modelo 2466',
				capacidad: '12.5 - 150 Lbs-pie / 17-203 Nm',
				longitud: '23.5"',
				url: 'torquimetros-digital-inalambrico.html',
				img: './images/torquimetros/torquimetro digital/torquimetro digital inalambrico.jpg',
				peso: '2.58 Kg',
			},
			{
				id: 29,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S290P',
				encastreEntrada: '1/2"',
				encastreSalida: '3/4"',
				max: '750',
				min: '227',
				'Torque de entrada': '227 Lbs-pie',
				'Torque de salida': '750 Lbs-pie',
				capacidad: '227 - 750 Lbs-pie / 307.77 - 1016.86 Nm',
				proporcion: '3.0:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador a.jpg',
				peso: '2.20 Kg',
			},
			{
				id: 30,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S291',
				encastreEntrada: '1/2"',
				encastreSalida: '3/4"',
				max: '1000',
				min: '303',
				'Torque de entrada': '303 Lbs-pie',
				'Torque de salida': '1000 Lbs-pie',
				capacidad: '303 - 1000 Lbs-pie / 410 - 1355.82',
				proporcion: '3.3:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador b.jpg',
				peso: '2.66 Kg',
			},
			{
				id: 31,
				alt: 'Multiplicador de torque encastre 3/4',
				nombre: 'Multiplicador de torque encastre 3/4"',
				modelo: 'modelo 9S292',
				encastreEntrada: '3/4"',
				encastreSalida: '1"',
				max: '2000',
				min: '571',
				'Torque de entrada': '571 Lbs-pie',
				'Torque de salida': '2000 Lbs-pie',
				capacidad: '571 - 2000 Lbs-pie / 774.17 - 2711.64 Nm',
				proporcion: '3.75:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador c.jpg',
				peso: '6.29 Kg',
			},
			{
				id: 32,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S391',
				encastreEntrada: '1/2"',
				encastreSalida: '3/4"',
				max: '1200',
				min: '200',
				'Torque de entrada': '200 Lbs-pie',
				'Torque de salida': '1200 Lbs-pie',
				capacidad: '200 - 1200 Lbs-pie / 271.16 - 1626.98 Nm',
				proporcion: '6:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador d.jpg',
				peso: '5.89 Kg',
			},
			{
				id: 33,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S392B',
				encastreEntrada: '1/2"',
				encastreSalida: '1"',
				max: '2200',
				min: '162',
				'Torque de entrada': '162 Lbs-pie',
				'Torque de salida': '2200 Lbs-pie',
				capacidad: '162 - 2200 Lbs-pie / 219.64 - 2982 Nm',
				proporcion: '13.6:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador e.jpg',
				peso: '9.35 Kg',
			},
			{
				id: 34,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S393A',
				encastreEntrada: '1/2"',
				encastreSalida: '1"',
				max: '3200',
				min: '173',
				'Torque de entrada': '173 Lbs-pie',
				'Torque de salida': '3200 Lbs-pie',
				capacidad: '173 - 3200 Lbs-pie / 234.56 - 4338.62 Nm',
				proporcion: '18.5:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador e.jpg',
				peso: '10.14 Kg',
			},
			{
				id: 35,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S394',
				encastreEntrada: '1/2"',
				encastreSalida: '1-1/2"',
				max: '5000',
				min: '189',
				'Torque de entrada': '189 Lbs-pie',
				'Torque de salida': '5000 Lbs-pie',
				capacidad: '189 - 5000 Lbs-pie / 256.25 - 6779.09 Nm',
				proporcion: '26.5:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador f.jpg',
				peso: '15.42 Kg',
			},
			{
				id: 36,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S395',
				encastreEntrada: '1/2"',
				encastreSalida: '1-1/2"',
				max: '8000',
				min: '154',
				'Torque de entrada': '154 Lbs-pie',
				'Torque de salida': '8000 Lbs-pie',
				capacidad: '154 - 8000 Lbs-pie / 208.8 - 10846.54 Nm',
				proporcion: '52.0:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador f.jpg',
				peso: '22.81 Kg',
			},
			{
				id: 37,
				alt: 'Multiplicador de torque encastre 1/2',
				nombre: 'Multiplicador de torque encastre 1/2"',
				modelo: 'modelo 9S492',
				encastreEntrada: '1/2"',
				encastreSalida: '1"',
				max: '2200',
				min: '162',
				'Torque de entrada': '162 Lbs-pie',
				'Torque de salida': '2200 Lbs-pie',
				capacidad: '162 - 2200 Lbs-pie / 219.64 - 2982.8 Nm',
				proporcion: '13.6:1',
				url: 'multiplicador-de-torque.html',
				img: './images/multiplicador/multiplicador/multiplicador g.jpg',
				peso: '7.80 Kg',
			},
			{
				id: 38,
				alt: 'Llave de control de torque electricas encastre 3/4',
				nombre: 'Llave de control de torque electricas encastre 3/4"',
				artN: '50 084 103',
				encastre: '3/4 ó 1"',
				max: '626',
				min: '110',
				modelo: 'modelo TESM-84',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '110.63 - 626.93 Lbs-pie / 150 - 850 Nm',
				peso: '10 kg',
			},
			{
				id: 39,
				alt: 'Llave de control de torque electricas encastre 1',
				nombre: 'Llave de control de torque electricas encastre 1"',
				artN: '50 105 113',
				encastre: '1"',
				max: '885',
				min: '206',
				modelo: 'modelo TESM-105',
				velocidad: '5 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '206.52 - 885.07 Lbs-pie / 280 - 1200 Nm',
				peso: '10 Kg',
			},
			{
				id: 40,
				alt: 'Llave de control de torque electricas encastre 1.1/2',
				nombre: 'Llave de control de torque electricas encastre 1.1/2"',
				artN: '50 335 133',
				encastre: '1.1/2"',
				max: '2581',
				min: '265',
				modelo: 'modelo TESM-355',
				velocidad: '3 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '265.52 - 2581.47 Lbs-pie / 360 - 3500 Nm',
				peso: '14.5 Kg',
			},
			{
				id: 41,
				alt: 'Llave de control de torque electricas encastre 1.1/2',
				nombre: 'Llave de control de torque electricas encastre 1.1/2"',
				artN: '50 505 143',
				encastre: '1.1/2"',
				max: '516',
				min: '36',
				modelo: 'modelo TESM-505',
				velocidad: '1.2 RPM',
				url: 'llave-de-control-de-torque-electrica.html',
				img: './images/llave/llave de control de torque electrica/llave de control de torque electrica.jpg',
				capacidad: '36.87 - 516.29 Lbs-pie / 50 - 700 Nm',
				peso: '16.7 Kg',
			},
			{
				id: 42,
				alt: 'Llave de control de torque inalambrico encastre 3/4',
				nombre: 'Llave de control de torque inalambrico encastre 3/4"',
				encastre: '3/4"',
				max: '958',
				min: '221',
				modelo: 'CP8613',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica a.jpg',
				capacidad: '221.27 - 958.83 libs-pie / 300 - 1300 Nm',
				peso: '5.3 Kg',
			},
			{
				id: 43,
				alt: 'Llave de control de torque inalambrico encastre 1',
				nombre: 'Llave de control de torque inalambrico encastre 1"',
				encastre: '1"',
				max: '1917',
				min: '516',
				modelo: 'CP8626',
				velocidad: '5 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica b.jpg',
				capacidad: '516.29 - 1917.66 Lbs-pie / 700 - 2600 Nm',
				peso: '7.2 Kg',
			},
			{
				id: 44,
				alt: 'Llave de control de torque inalambrico encastre 1',
				nombre: 'Llave de control de torque inalambrico encastre 1"',
				encastre: '1"',
				max: '3024',
				min: '737',
				modelo: 'CP8641',
				velocidad: '3 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica c.jpg',
				capacidad: '737.56 - 3024 Lbs-pie / 1000 - 4100 Nm',
				peso: '11.4 Kg',
			},
			{
				id: 45,
				alt: 'Llave de control de torque inalambrico encastre 1 ó 1.1/2',
				nombre: 'Llave de control de torque inalambrico encastre 1 ó 1.1/2"',
				encastre: '1" ó 1.1/2"',
				max: '5974',
				min: '1917',
				modelo: 'CP8681',
				velocidad: '1.2 RPM',
				url: 'llave-de-control-de-torque-a-bateria.html',
				img: './images/llave/llaves control de torque inalambrica/llaves control de torque inalambrica d.jpg',
				capacidad: '1917.66 - 5974.25 Lbs-pie / 2600-8100 Nm',
				peso: '16.5 Kg',
			},
			{
				id: 46,
				alt: 'Llave de control de torque neumatica encastre 3/4',
				nombre: 'Llave de control de torque neumatica encastre 3/4"',
				artN: '615 180 0120',
				max: '1300',
				min: '236',
				modelo: 'CP6613',
				encastre: '3/4"',
				velocidad: '20 RPM',
				url: 'llave-de-control-de-torque-neumatica.html',
				img: './images/llave/multiplicador/multiplicador.jpg',
				capacidad: '236.02 - 958.83 Lbs-pie / 320 - 1300 Nm',
				peso: '4.4 Kg',
			},
			{
				id: 47,
				alt: 'Llave de control de torque neumatica encastre 1',
				nombre: 'Llave de control de torque neumatica encastre 1"',
				artN: '615 180 0130',
				max: '1917',
				min: '516',
				modelo: 'CP6626',
				encastre: '1"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-neumatica.html',
				img: './images/llave/multiplicador/multiplicador.jpg',
				capacidad: '516.29 - 1917.66 Lbs-pie / 700 - 2600 Nm',
				peso: '5.7 Kg',
			},
			{
				id: 48,
				alt: 'Llave de control de torque neumatica encastre 1',
				nombre: 'Llave de control de torque neumatica encastre 1"',
				artN: '615 180 0140',
				max: '3024',
				min: '737',
				modelo: 'CP6641',
				encastre: '1"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-neumatica.html',
				img: './images/llave/multiplicador/multiplicador.jpg',
				capacidad: '737.56 - 3024 Lbs-pie / 1000 - 4100 Nm',
				peso: '11.4 Kg',
			},
			{
				id: 49,
				alt: 'Llave de control de torque hidraulica encastre 1 o 1.1/2',
				nombre: 'Llave de control de torque hidraulica encastre 1 o 1.1/2"',
				artN: '71 051 000',
				max: '3614',
				min: '236',
				modelo: 'BL-51',
				encastre: '1 ó 1.1/2"',
				velocidad: '20 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '236.02 - 3614.05 Lbs-pie / 320 - 4900 Nm',
				peso: '4.9 Kg',
			},
			{
				id: 50,
				alt: 'Llave de control de torque hidraulica encastre 1.1/2',
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2"',
				artN: '71 052 000',
				max: '3835',
				min: '236',
				modelo: 'BL-52',
				encastre: '1.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '236.02 - 3835.32 Lbs-pie / 320 - 5200 Nm',
				peso: '5.4 Kg',
			},
			{
				id: 51,
				alt: 'Llave de control de torque hidraulica encastre 1.1/2',
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2"',
				artN: '71 082 000',
				max: '3024',
				min: '737',
				modelo: 'BL-82',
				encastre: '1.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '737.56 - 3024 Lbs-pie / 1000 - 4100 Nm',
				peso: '7.8 Kg',
			},
			{
				id: 52,
				alt: 'Llave de control de torque hidraulica encastre 1.1/2',
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2"',
				artN: '71 102 000',
				max: '737',
				min: '324',
				modelo: 'BL-102',
				encastre: '1.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '324.53 - 737.56 Lbs-pie / 440 - 1000 Nm',
				peso: '7.8 Kg',
			},
			{
				id: 53,
				alt: 'Llave de control de torque hidraulica encastre 1.1/2 ó 2.1/2',
				nombre: 'Llave de control de torque hidraulica encastre 1.1/2 ó 2.1/2"',
				artN: '71 152 000',
				max: '11210',
				min: '700',
				modelo: 'BL-152',
				encastre: '1.1/2 ó 2.1/2"',
				velocidad: '10 RPM',
				url: 'llave-de-control-de-torque-hidraulica.html',
				img: './images/llave/llave de control de torque hidraulica/llave de control de torque hidraulica.jpg',
				capacidad: '700.68 - 11210.94 Lbs-pie / 950 - 15200 Nm',
				peso: '12 Kg',
			},
		],
		keys: ['nombre', 'modelo', 'capacidad'],
		cache: true,
		submit: true,
	},
	resultsList: {
		element: (list, data) => {
			if (!data.results.length) {
				// Create "No Results" message element
				const message = document.createElement('div');
				// Add class to the created element
				message.setAttribute('class', 'no_result');
				// Add message text content
				message.innerHTML = `<span>Found No Results for "${data.query}"</span>`;
				// Append message element to the results list
				list.prepend(message);
			}
		},
		noResults: true,
		maxResults: 50,
		tabSelect: true,
	},
	resultItem: {
		highlight: true,
	},
	events: {
		input: {
			selection: (event) => {
				console.log(event, 'aqui esta el evento');
				const selection = event.detail.selection.value;
				autoCompleteJS.input.value = selection.nombre;
				let containerList = document.getElementById('list-items');

				if (selection.encastreEntrada && selection.encastreSalida) {
					containerList.innerHTML = `
					<a href="${selection.url}"  class="list-items__container-item" id="">
							<img class="img-herramientas" src="${selection.img}" alt="${selection.alt}" srcset="" />
							<h3>${selection.nombre}</h3>
							<p>${selection.modelo}</p>
							<div class="list-items__content" id="list-items__content">
								<p><b>Encastre entrada:</b>  ${selection.encastreEntrada}</p>
								<p><b>Encastre salida:</b>  ${selection.encastreSalida}</p>
								<p><b>capacidad:</b>  ${selection.capacidad}</p>
								<p><b>peso:</b> ${selection.peso}</p>
							</div>
						</a>
						`;
					console.log('existe longitud');
				}
				if (selection.longitud !== undefined) {
					containerList.innerHTML = `
					<a href="${selection.url}"  class="list-items__container-item" id="">
							<img class="img-herramientas" src="${selection.img}" alt="${selection.alt}" srcset="" />
							<h3>${selection.nombre}</h3>
							<p>${selection.modelo}</p>
							<div class="list-items__content" id="list-items__content">
								<p><b>Tipo:</b>  ${selection.tipo}</p>
								<p><b>Capacidad:</b> <br>  ${selection.capacidad}</p>
								<p><b>Longitud:</b> ${selection.longitud}</p>
								<p><b>Peso:</b> ${selection.peso}</p>
							</div>
						</a>
						`;
					console.log('no existe');
				}
				if (selection.artN) {
					containerList.innerHTML = `
					<a href="${selection.url}"  class="list-items__container-item" id="">
							<img class="img-herramientas" src="${selection.img}" alt="${selection.alt}" srcset="" />
							<h3>${selection.nombre}</h3>
							<p>${selection.modelo}</p>
							<div class="list-items__content" id="list-items__content">
								<p><b>Capacidad:</b> ${selection.capacidad}</p>
								<p><b>Art N°:</b> ${selection.artN}</p>
								<p><b>Peso:</b> ${selection.peso}</p>
							</div>
						</a>
						`;
					console.log('no existe');
				}
			},
		},
	},
});
